version: "3.8"
services:
    mongodb:
        image : mongo:latest
        environment:
            # provide your credentials here
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rates
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./db/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped